COLUMN_FORMAT_DATETIME = 'date-time'
COLUMN_FORMAT_UUID = 'uuid'

COLUMN_TYPE_ARRAY = 'array'
COLUMN_TYPE_BINARY = 'binary'
COLUMN_TYPE_BOOLEAN = 'boolean'
COLUMN_TYPE_INTEGER = 'integer'
COLUMN_TYPE_NULL = 'null'
COLUMN_TYPE_NUMBER = 'number'
COLUMN_TYPE_OBJECT = 'object'
COLUMN_TYPE_STRING = 'string'

COLUMN_TYPES = [
  COLUMN_TYPE_ARRAY,
  COLUMN_TYPE_BINARY,
  COLUMN_TYPE_BOOLEAN,
  COLUMN_TYPE_INTEGER,
  COLUMN_TYPE_NULL,
  COLUMN_TYPE_NUMBER,
  COLUMN_TYPE_OBJECT,
  COLUMN_TYPE_STRING,
]

DATABASE_TYPE_DYNAMODB = 'dynamodb'

FILE_TYPE_CSV = 'csv'
FILE_TYPE_PARQUET = 'parquet'

INCLUSION_AUTOMATIC = 'automatic'
INCLUSION_AVAILABLE = 'available'
INCLUSION_UNSUPPORTED = 'unsupported'

METADATA_KEY_INCLUSION = 'inclusion'
METADATA_KEY_SELECTED = 'selected'

REPLICATION_METHOD_FULL_TABLE = 'FULL_TABLE'
REPLICATION_METHOD_INCREMENTAL = 'INCREMENTAL'
REPLICATION_METHOD_LOG_BASED = 'LOG_BASED'

UNIQUE_CONFLICT_METHOD_IGNORE = 'IGNORE'
UNIQUE_CONFLICT_METHOD_UPDATE = 'UPDATE'

BATCH_FETCH_LIMIT = 50000
SUBBATCH_FETCH_LIMIT = 10000
BATCH_FETCH_LIMIT_KEY = 'batch_fetch_limit'
SUBBATCH_FETCH_LIMIT_KEY = 'subbatch_fetch_limit'
