description: Next Best Action Template
name: next_best_action
pipeline:
  blocks:
  - all_upstream_blocks_executed: true
    color: null
    configuration: {}
    downstream_blocks:
    - confident_portal
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: fancy dream
    retry_config: null
    status: not_executed
    timeout: null
    type: data_loader
    upstream_blocks: []
    uuid: fancy_dream
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - elven_ring
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: confident portal
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - fancy_dream
    uuid: confident_portal
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - enchanting_inventor
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: elven ring
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - confident_portal
    uuid: elven_ring
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - ornate_fire
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: enchanting inventor
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - elven_ring
    uuid: enchanting_inventor
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - peaceful_elm
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: ornate fire
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - enchanting_inventor
    uuid: ornate_fire
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - rough_quest
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: peaceful elm
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - ornate_fire
    uuid: peaceful_elm
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - resolute_voice
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: rough quest
    retry_config: null
    status: not_executed
    timeout: null
    type: model_maker
    upstream_blocks:
    - peaceful_elm
    uuid: rough_quest
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: resolute voice
    retry_config: null
    status: not_executed
    timeout: null
    type: data_exporter
    upstream_blocks:
    - rough_quest
    uuid: resolute_voice
  cache_block_output_in_memory: false
  callbacks: []
  concurrency_config: {}
  conditionals: []
  created_at: '2026-04-09 20:47:01.259300+00:00'
  data_integration: null
  description: Create from "Next Best Action Template"
  executor_config: {}
  executor_count: 1
  executor_type: null
  extensions: {}
  name: next_best_action
  notification_config: {}
  remote_variables_dir: null
  retry_config: {}
  run_pipeline_in_one_process: false
  settings:
    triggers: null
  spark_config: {}
  tags:
  - next-best-action
  - from-template
  type: python
  uuid: next_best_action
  variables_dir: /home/src/mage_data/b2mage-base
  widgets: []
tags: []
user:
  username: admin
