DESTINATIONS = [
    dict(name='Amazon S3'),
    dict(name='BigQuery'),
    dict(name='Clickhouse'),
    dict(name='Delta Lake S3'),
    dict(name='Google Cloud Storage'),
    dict(name='MongoDB'),
    dict(
        module_name='MSSQL',
        name='Microsoft SQL Server',
        uuid='mssql',
    ),
    dict(name='MySQL'),
    dict(name='OracleDB'),
    dict(name='PostgreSQL'),
    dict(name='Redshift'),
    dict(name='Salesforce'),
    dict(name='Snowflake'),
    dict(name='Trino'),
]
