triggers:
- description: null
  envs: []
  last_enabled_at: null
  name: bitter merchant
  pipeline_uuid: example_pipeline
  schedule_interval: null
  schedule_type: null
  settings: null
  sla: null
  start_time: null
  status: inactive
  token: null
  variables: null
