changelog:
  exclude:
    labels:
      - documentation
  categories:
    - title: 🎉 Exciting New Features 
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 💅 Enhancements & Polish
      labels:
        - enhancements
    - title: Other Changes
      labels:
        - "*"
