import os

KUBE_POD_NAME_ENV_VAR = 'HOSTNAME'
KUBE_POD_NAMESPACE_ENV_VAR = 'KUBE_NAMESPACE'
KUBE_CONTAINER_NAME = os.getenv('MAGE_CONTAINER_NAME', '')
CONFIG_FILE = os.getenv('K8S_CONFIG_FILE', '')

DEFAULT_NAMESPACE = os.getenv(KUBE_POD_NAMESPACE_ENV_VAR, 'default')
DEFAULT_SERVICE_ACCOUNT_NAME = os.getenv('KUBE_SERVICE_ACCOUNT_NAME', 'default')
DEFAULT_STORAGE_CLASS_NAME = os.getenv('KUBE_STORAGE_CLASS_NAME', 'default')
