description: Demand Forecasting Template
name: demand_forecasting
pipeline:
  blocks:
  - all_upstream_blocks_executed: true
    color: null
    configuration: {}
    downstream_blocks:
    - broken_mana
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: victorious dew
    retry_config: null
    status: not_executed
    timeout: null
    type: data_loader
    upstream_blocks: []
    uuid: victorious_dew
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - renewed_brook
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: broken mana
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - victorious_dew
    uuid: broken_mana
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - whimsical_feather
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: renewed brook
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - broken_mana
    uuid: renewed_brook
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - humble_herbalist
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: whimsical feather
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - renewed_brook
    uuid: whimsical_feather
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - halcyon_dawn
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: humble herbalist
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - whimsical_feather
    uuid: humble_herbalist
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - wistful_byte
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: halcyon dawn
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - humble_herbalist
    uuid: halcyon_dawn
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - astonishing_warrior
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: wistful byte
    retry_config: null
    status: not_executed
    timeout: null
    type: model_maker
    upstream_blocks:
    - halcyon_dawn
    uuid: wistful_byte
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: astonishing warrior
    retry_config: null
    status: not_executed
    timeout: null
    type: data_exporter
    upstream_blocks:
    - wistful_byte
    uuid: astonishing_warrior
  cache_block_output_in_memory: false
  callbacks: []
  concurrency_config: {}
  conditionals: []
  created_at: '2026-04-10 05:21:39.371771+00:00'
  data_integration: null
  description: Created from "Demand Forecasting Template"
  executor_config: {}
  executor_count: 1
  executor_type: null
  extensions: {}
  name: demand_forecasting
  notification_config: {}
  remote_variables_dir: null
  retry_config: {}
  run_pipeline_in_one_process: false
  settings:
    triggers: null
  spark_config: {}
  tags:
  - demand
  - from-template
  type: python
  uuid: demand_forecasting
  variables_dir: /home/src/mage_data/b2mage-base
  widgets: []
tags: []
user:
  username: admin
