description: Next Best Offer Template
name: next_best_offer
pipeline:
  blocks:
  - all_upstream_blocks_executed: true
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - duplicate_cleaner
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: data loader
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: data_loader
    upstream_blocks: []
    uuid: data_loader
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - missing_value_handler
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: duplicate cleaner
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: transformer
    upstream_blocks:
    - data_loader
    uuid: duplicate_cleaner
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - dtype_optimizer
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: missing value handler
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: transformer
    upstream_blocks:
    - duplicate_cleaner
    uuid: missing_value_handler
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - outlier_handler
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: dtype optimizer
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: transformer
    upstream_blocks:
    - missing_value_handler
    uuid: dtype_optimizer
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - feature_engineer
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: outlier handler
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: transformer
    upstream_blocks:
    - dtype_optimizer
    uuid: outlier_handler
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - model
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: feature engineer
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: transformer
    upstream_blocks:
    - outlier_handler
    uuid: feature_engineer
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - data_exporter
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: model
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: model_maker
    upstream_blocks:
    - feature_engineer
    uuid: model
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: data exporter
    pipelines: []
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: data_exporter
    upstream_blocks:
    - model
    uuid: data_exporter
  cache_block_output_in_memory: false
  callbacks: []
  concurrency_config: {}
  conditionals: []
  created_at: '2026-04-14 12:01:50.979881+00:00'
  data_integration: null
  description: Created from "Next Best Offer" Template
  executor_config: {}
  executor_count: 1
  executor_type: null
  extensions: {}
  name: next_best_offer
  notification_config: {}
  remote_variables_dir: null
  retry_config: {}
  run_pipeline_in_one_process: false
  settings:
    triggers: null
  spark_config: {}
  tags:
  - next-best-offer
  - from-a-template
  type: python
  uuid: next_best_offer
  variables_dir: /home/src/mage_data/b2mage-base
  widgets: []
tags: []
user:
  username: admin
