name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: PROJECT_ID
  GAR_LOCATION: GAR_LOCATION
  REPOSITORY: REPOSITORY
  IMAGE: IMAGE

jobs:
  build-and-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        token_format: access_token

    - uses: docker/login-action@v1
      name: Docker login
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Docker build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}" \
          .

    - name: Docker push
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}"

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: mage-data-prep
        image: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}
