name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - master

env:
  GAR_LOCATION: GAR_LOCATION
  GOOGLE_CLOUD_RUN_SERVICE_NAME: GOOGLE_CLOUD_RUN_SERVICE_NAME
  IMAGE: IMAGE
  PROJECT_ID: PROJECT_ID
  REPOSITORY: REPOSITORY

jobs:
  build-and-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        token_format: access_token

    - uses: docker/login-action@v1
      name: Docker login
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Docker build
      run: |-
        docker build \
          --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" \
          .

    - name: Docker push
      run: |-
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.GOOGLE_CLOUD_RUN_SERVICE_NAME }}
        image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
        region: ${{ env.GAR_LOCATION }}
    
    # Uncomment the step below if you are using a DBT docs service
    # - id: deploy-docs
    #   uses: google-github-actions/deploy-cloudrun@v0
    #   with:
    #     service: ${{ env.GOOGLE_CLOUD_RUN_SERVICE_NAME }}-docs
    #     image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
    #     region: ${{ env.GAR_LOCATION }}
