GHE_CLIENT_ID = 'GHE_CLIENT_ID'
GHE_CLIENT_SECRET = 'GHE_CLIENT_SECRET'
GHE_HOSTNAME = 'GHE_HOSTNAME'

GITLAB_HOST = 'GITLAB_HOST'
GITLAB_CLIENT_ID = 'GITLAB_CLIENT_ID'
GITLAB_CLIENT_SECRET = 'GITLAB_CLIENT_SECRET'

BITBUCKET_HOST = 'BITBUCKET_HOST'
BITBUCKET_OAUTH_KEY = 'BITBUCKET_OAUTH_KEY'
BITBUCKET_OAUTH_SECRET = 'BITBUCKET_OAUTH_SECRET'

GIT_SSH_PUBLIC_KEY = 'GIT_SSH_PUBLIC_KEY'
GIT_SSH_PRIVATE_KEY = 'GIT_SSH_PRIVATE_KEY'
GIT_ACCESS_TOKEN = 'GIT_ACCESS_TOKEN'
