import * as osPath from 'path';


import { groupBy, sortByKey } from '@utils/array';
import { getFileExtension } from '@storage/files';
import { dig } from '@utils/hash';



const arr1 =
[
"fire/water/ice/sword/scratchpads/gleeful_warrior.py",
"fire/water/ice/sword/scratchpads/epic_wizard.py",
"fire/water/ice/sword/scratchpads/crystal_scholar.py",
"fire/water/ice/sword/scratchpads/__init__.py",
"fire/water/ice/sword/data_loaders/volcanic_oracle.sql",
"fire/water/ice/sword/data_loaders/versatile_willow.py",
"fire/water/ice/sword/data_loaders/pristine_lake.sql",
"fire/water/ice/sword/data_loaders/normal.py",
"fire/water/ice/sword/data_loaders/dynamic_b.py",
"fire/water/ice/sword/data_loaders/dynamic_a.py",
"fire/water/ice/sword/data_loaders/dy_parent.py",
"fire/water/ice/sword/data_loaders/default_repo/data_loaders/dynamic_parent_b.py",
"fire/water/ice/sword/data_loaders/__init__.py",
"fire/water/ice/sword/data_exporters/export_titanic_clean.py",
"fire/water/ice/sword/data_exporters/child_reduce.py",
"fire/water/ice/sword/data_exporters/__init__.py",
"fire/water/ice/sword/aws/python/event_handler.py",
"fire/water/ice/sword/aws/env_vars.json",
"fire/water/ice/sword/aws-eks/kube/service.yaml",
"fire/water/ice/sword/aws-eks/kube/efs-pvc.yaml",
"fire/water/ice/sword/aws-eks/kube/deploy.yaml",
"fire/water/ice/sword/aws-dev/python/event_handler.py",
"fire/water/ice/sword/aws-dev/env_vars.json",
"fire/water/ice/sword/README.md",
"fire/transformers/dynamic_child_b.py",
"fire/transformers/dynamic_child_a.py",
"fire/transformers/dy_squared.py",
"fire/transformers/child_upstreams.py",
"fire/transformers/__init__.py",
"fire/teams/growth/demo/target/semantic_manifest.json",
"fire/teams/growth/demo/target/run_results.json",
"fire/teams/growth/demo/target/run/demo/models/example/users.sql",
"fire/teams/growth/demo/target/run/demo/models/example/my_second_dbt_model.sql",
"fire/teams/growth/demo/target/manifest.json",
"fire/teams/growth/demo/target/graph_summary.json",
"fire/teams/growth/demo/target/compiled/demo/models/example/users.sql",
"fire/teams/growth/demo/target/compiled/demo/models/example/schema.yml/unique_my_second_dbt_model_id.sql",
"fire/teams/growth/demo/target/compiled/demo/models/example/schema.yml/unique_my_first_dbt_model_id.sql",
"fire/teams/growth/demo/target/compiled/demo/models/example/schema.yml/not_null_my_second_dbt_model_id.sql",
"fire/teams/growth/demo/target/compiled/demo/models/example/schema.yml/not_null_my_first_dbt_model_id.sql",
"fire/teams/growth/demo/target/compiled/demo/models/example/my_second_dbt_model.sql",
"fire/teams/growth/demo/target/compiled/demo/models/example/my_first_dbt_model.sql",
"fire/teams/growth/demo/models/example/users.sql",
"fire/teams/growth/demo/models/example/my_second_dbt_model.sql",
"fire/teams/growth/demo/README.md",
"fire/settings.yaml",
"fire/scratchpads/gleeful_warrior.py",
"fire/scratchpads/epic_wizard.py",
"fire/scratchpads/crystal_scholar.py",
"fire/scratchpads/__init__.py",
"fire/pipelines/unstoppable_snowflake/metadata.yaml",
"fire/pipelines/unstoppable_snowflake/interactions.yaml",
"fire/pipelines/unstoppable_snowflake/__init__.py",
"fire/pipelines/test_sql/metadata.yaml",
"fire/pipelines/test_sql/interactions.yaml",
"fire/pipelines/test_sql/__init__.py",
"fire/pipelines/test/metadata.yaml",
"fire/pipelines/test/__init__.py",
"fire/pipelines/sublime_morning/metadata.yaml",
"fire/pipelines/sublime_morning/interactions.yaml",
"fire/pipelines/sublime_morning/__init__.py",
"fire/pipelines/sql_block_test/metadata.yaml",
"fire/pipelines/sql_block_test/interactions.yaml",
"fire/pipelines/sql_block_test/__init__.py",
"fire/pipelines/spring_oracle/metadata.yaml",
"fire/pipelines/spring_oracle/interactions.yaml",
"fire/pipelines/spring_oracle/__init__.py",
"fire/pipelines/quiet_meadow/metadata.yaml",
"fire/pipelines/quiet_meadow/interactions.yaml",
"fire/pipelines/quiet_meadow/__init__.py",
"fire/pipelines/precise_realm/metadata.yaml",
"fire/pipelines/precise_realm/interactions.yaml",
"fire/pipelines/precise_realm/__init__.py",
"fire/pipelines/old_silversmith/metadata.yaml",
"fire/pipelines/old_silversmith/interactions.yaml",
"fire/pipelines/old_silversmith/__init__.py",
"fire/pipelines/melodious_sorcerer/metadata.yaml",
"fire/pipelines/melodious_sorcerer/interactions.yaml",
"fire/pipelines/melodious_sorcerer/__init__.py",
"fire/pipelines/lyrical_brook/metadata.yaml",
"fire/pipelines/lyrical_brook/__init__.py",
"fire/pipelines/knightly_myth/metadata.yaml",
"fire/pipelines/knightly_myth/interactions.yaml",
"fire/pipelines/knightly_myth/__init__.py",
"fire/pipelines/impressive_paper/metadata.yaml",
"fire/pipelines/impressive_paper/__init__.py",
"fire/pipelines/honorable_snowflake/metadata.yaml",
"fire/pipelines/honorable_snowflake/interactions.yaml",
"fire/pipelines/honorable_snowflake/__init__.py",
"fire/pipelines/funoneyes_______/metadata.yaml",
"fire/pipelines/funoneyes_______/__init__.py",
"fire/pipelines/ephemeral_noble/metadata.yaml",
"fire/pipelines/ephemeral_noble/__init__.py",
"fire/pipelines/dynamic_replica_blocks/metadata.yaml",
"fire/pipelines/dynamic_replica_blocks/interactions.yaml",
"fire/pipelines/dynamic_replica_blocks/__init__.py",
"fire/pipelines/dbt_old/metadata.yaml",
"fire/pipelines/dbt_old/interactions.yaml",
"fire/pipelines/dbt_old/__init__.py",
"fire/pipelines/dbt_dx_2/metadata.yaml",
"fire/pipelines/dbt_dx_2/interactions.yaml",
"fire/pipelines/dbt_dx_2/__init__.py",
"fire/pipelines/cozy_sky/metadata.yaml",
"fire/pipelines/cozy_sky/__init__.py",
"fire/pipelines/colossal_core/metadata.yaml",
"fire/pipelines/colossal_core/__init__.py",
"fire/pipelines/colossal_aspen/metadata.yaml",
"fire/pipelines/colossal_aspen/__init__.py",
"fire/pipelines/beaming_herbalist/metadata.yaml",
"fire/pipelines/beaming_herbalist/__init__.py",
"fire/pipelines/autumn_dream/metadata.yaml",
"fire/pipelines/autumn_dream/interactions.yaml",
"fire/pipelines/autumn_dream/__init__.py",
"fire/pipelines/astral_field/metadata.yaml",
"fire/pipelines/astral_field/interactions.yaml",
"fire/pipelines/astral_field/__init__.py",
"fire/pipelines/astonishing_leaf/metadata.yaml",
"fire/pipelines/astonishing_leaf/__init__.py",
"fire/pipelines/add_default_blocks_to_every_pipeline/metadata.yaml",
"fire/pipelines/add_default_blocks_to_every_pipeline/__init__.py",
"fire/models/mage_sourcsssssssssssssssses11111111.yaml",
"fire/models/mage_sources11111111.yaml",
"fire/models/mage_sources.yaml",
"fire/models/__init__.py",
"fire/metadata.yaml",
"fire/io_config.yaml",
"fire/global_hooks.yaml",
"fire/dbts/virtuous_arcanist.yaml",
"fire/dbts/sparkling_breeze.yaml",
"fire/dbts/shining_dawn.yaml",
"fire/dbts/righteous_merchant.yaml",
"fire/dbts/resilient_tree.yaml",
"fire/dbts/opaque_arcanist.yaml",
"fire/dbts/mage_sourcsssssssssssssssses11111111.yaml",
"fire/dbts/mage_sources11111111.yaml",
"fire/dbts/mage_sources.yaml",
"fire/dbts/knightly_grace.yaml",
"fire/dbts/happy_river.yaml",
"fire/dbts/dauntless_explorer.yaml",
"fire/dbts/cheerful_phoenix.yaml",
"fire/dbts/__init__.py",
"fire/dbt/test2/target/semantic_manifest.json",
"fire/dbt/test2/target/manifest.json",
"fire/dbt/test2/target/graph_summary.json",
"fire/dbt/test2/models/example/my_second_dbt_model.sql",
"fire/dbt/test2/models/example/my_first_dbt_model.sql",
"fire/dbt/test2/README.md",
"fire/dbt/test/target/semantic_manifest.json",
"fire/dbt/test/target/run_results.json",
"fire/dbt/test/target/run/test/models/example/my_second_dbt_model.sql",
"fire/dbt/test/target/run/test/models/example/my_first_dbt_model.sql",
"fire/dbt/test/target/manifest.json",
"fire/dbt/test/target/graph_summary.json",
"fire/dbt/test/target/compiled/test/models/example/schema.yml/unique_my_first_dbt_model_id.sql",
"fire/dbt/test/target/compiled/test/models/example/schema.yml/not_null_my_first_dbt_model_id.sql",
"fire/dbt/test/target/compiled/test/models/example/my_second_dbt_model.sql",
"fire/dbt/test/target/compiled/test/models/example/my_first_dbt_model.sql",
"fire/dbt/test/models/example/my_second_dbt_model.sql",
"fire/dbt/test/models/example/my_first_dbt_model.sql",
"fire/dbt/test/dbt/demo/target/semantic_manifest.json",
"fire/dbt/test/dbt/demo/target/run_results.json",
"fire/dbt/test/dbt/demo/target/manifest.json",
"fire/dbt/test/dbt/demo/target/graph_summary.json",
"fire/dbt/test/dbt/demo/models/example/my_second_dbt_model.sql",
"fire/dbt/test/dbt/demo/models/example/my_first_dbt_model.sql",
"fire/dbt/test/dbt/demo/README.md",
"fire/dbt/test/data_exporters/export_titanic_clean.py",
"fire/dbt/test/data_exporters/child_reduce.py",
"fire/dbt/test/data_exporters/__init__.py",
"fire/dbt/test/README.md",
"fire/data_loaders/water/more.py",
"fire/data_loaders/water/fire/default_repo/transformers/old_sound.py",
"fire/data_loaders/water/fire/default_repo/transformers/morning_grass.py",
"fire/data_loaders/water/fire/default_repo/transformers/fill_in_missing_values.py",
"fire/data_loaders/water/fire/default_repo/transformers/black_sound.py",
"fire/data_loaders/water/fire/default_repo/transformers/__init__.py",
"fire/data_loaders/water/fire/default_repo/sensors/misty_water.py",
"fire/data_loaders/water/fire/default_repo/sensors/__init__.py",
"fire/data_loaders/water/fire/default_repo/scratchpads/__init__.py",
"fire/data_loaders/water/fire/default_repo/requirements.txt",
"fire/data_loaders/water/fire/default_repo/pipelines/zendesk_to_postgres/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/zendesk_to_postgres/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/testing/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/testing/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/stripe_to_snowflake/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/stripe_to_snowflake/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/salesforce_to_bigquery/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/salesforce_to_bigquery/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/s3_to_postgres/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/s3_to_postgres/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/s3_to_bigquery/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/s3_to_bigquery/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_snowflake/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_snowflake/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_postgres/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_postgres/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_delta_lake_s3/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_delta_lake_s3/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_bigquery/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/postgres_to_bigquery/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/polished_silence/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/polished_silence/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/intercom_snowflake/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/intercom_snowflake/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/google_sheets/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/google_sheets/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/google_analytics_postgresql_dw/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/google_analytics_postgresql_dw/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/freshdesk_to_postgres/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/freshdesk_to_postgres/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/bigquery_to_postgres/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/bigquery_to_postgres/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/api_mysql/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/api_mysql/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/amplitude_to_mysql/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/amplitude_to_mysql/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/amplitude_postgresql_dw/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/pipelines/amplitude_postgresql_dw/__init__.py",
"fire/data_loaders/water/fire/default_repo/pipelines/__init__.py",
"fire/data_loaders/water/fire/default_repo/metadata.yaml",
"fire/data_loaders/water/fire/default_repo/io_config.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/winter_shadow.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/twilight_dawn.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/spring_voice.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/solitary_dream.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/solitary_cloud.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/small_voice.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/silent_leaf.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/rough_firefly.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/red_wildflower.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/quiet_haze.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/purple_wood.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/old_field.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/morning_star.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/load_titanic.py",
"fire/data_loaders/water/fire/default_repo/data_loaders/load_fake_data_from_api.py",
"fire/data_loaders/water/fire/default_repo/data_loaders/little_sun.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/hidden_cloud.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/google_sheets.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/google_analytics.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/falling_smoke.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/falling_bird.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/bold_dream.py",
"fire/data_loaders/water/fire/default_repo/data_loaders/autumn_sun.py",
"fire/data_loaders/water/fire/default_repo/data_loaders/amplitude.yaml",
"fire/data_loaders/water/fire/default_repo/data_loaders/__init__.py",
"fire/data_loaders/water/fire/default_repo/data_exporters/withered_sun.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/winter_moon.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/weathered_tree.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/throbbing_leaf.py",
"fire/data_loaders/water/fire/default_repo/data_exporters/shy_breeze.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/postgresql_dw.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/old_silence.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/nameless_fire.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/muddy_pine.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/holy_moon.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/frosty_glitter.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/fragrant_moon.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/fragrant_glitter.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/export_titanic_clean.py",
"fire/data_loaders/water/fire/default_repo/data_exporters/dry_sun.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/broken_river.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/bold_waterfall.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/autumn_wood.yaml",
"fire/data_loaders/water/fire/default_repo/data_exporters/__init__.py",
"fire/data_loaders/water/fire/default_repo/charts/__init__.py",
"fire/data_loaders/water/fire/default_repo/__init__.py",
"fire/data_loaders/water/fire/aws/python/event_handler.py",
"fire/data_loaders/water/fire/aws/env_vars.json",
"fire/data_loaders/water/fire/aws-eks/kube/service.yaml",
"fire/data_loaders/water/fire/aws-eks/kube/efs-pvc.yaml",
"fire/data_loaders/water/fire/aws-eks/kube/deploy.yaml",
"fire/data_loaders/water/fire/aws-dev/python/event_handler.py",
"fire/data_loaders/water/fire/aws-dev/env_vars.json",
"fire/data_loaders/water/fire/README.md",
"fire/data_loaders/volcanic_oracle.sql",
"fire/data_loaders/valorous_spellcaster.sql",
"fire/data_loaders/super_star.py",
"fire/data_loaders/refined_wildflower.py",
"fire/data_loaders/pristine_lake.sql",
"fire/data_loaders/playful_illusion.py",
"fire/data_loaders/normal.py",
"fire/data_loaders/moonlit_star.py",
"fire/data_loaders/intriguing_familiar.py",
"fire/data_loaders/icy_haze.py",
"fire/data_loaders/hidden_paper.py",
"fire/data_loaders/exquisite_violet.py",
"fire/data_loaders/electrifying_ancient.py",
"fire/data_loaders/dynamic_b.py",
"fire/data_loaders/dynamic_a.py",
"fire/data_loaders/dy_parent.py",
"fire/data_loaders/default_repo/data_loaders/dynamic_parent_b.py",
"fire/data_loaders/charmed_night.py",
"fire/data_loaders/aged_glade.sql",
"fire/data_loaders/__init__.py",
"fire/data_exporters/pleasant_sea.py",
"fire/data_exporters/normal_c.py",
"fire/data_exporters/normal_a.py",
"fire/data_exporters/halcyon_brook.py",
"fire/data_exporters/dy_child.py",
"fire/data_exporters/__init__.py",
"fire/custom/weathered_familiar.py",
"fire/custom/relaxed_noble.py",
"fire/custom/insightful_sea.py",
"fire/custom/fantastic_crafter.py",
"fire/custom/add_blocks_to_pipeline.py",
"fire/custom/__init__.py",
"fire/conditionals/stop.py",
"fire/conditionals/__init__.py",
"fire/callbacks/righteous_frog.py",
"fire/callbacks/gracious_spell.py",
"fire/callbacks/effortless_prophecy.py",
"fire/callbacks/__init__.py",
"fire/Nones/mellow_flower.py",
"fire/Nones/holy_ronin.py",
"fire/Nones/__init__.py",
]
// const arr = sortByKey(arr1, i => i, { ascending: false })

function groupByCommonDirectories(arr) {

  const groupsWith1Directory = {};
  const group1Roots = [];

  const groupsWith2Directories = {};
  const group2Roots = [];


  arr?.forEach((filePath) => {
    const parts = filePath?.split(osPath.sep)?.slice(1);
    const count = parts?.length || 0;

    const parts1 = parts?.slice(0, count - 2);
    const parts2 = parts?.slice(0, count - 3);

    const key1 = parts1?.join(osPath.sep);
    const key2 = parts2?.join(osPath.sep);

    groupsWith1Directory[key1] = groupsWith1Directory[key1] || [];
    groupsWith2Directories[key2] = groupsWith2Directories[key2] || [];

    if (!parts1?.length) {
      group1Roots.push(filePath)
    } else {
      groupsWith1Directory[key1].push(filePath);
    }

    if (!parts2?.length) {
      group2Roots.push(filePath);
    } else {
      groupsWith2Directories[key2].push(filePath);
    };
  });

  return {
    groupsWith1Directory,
    groupsWith2Directories,
  };
}

const groupsbyFX = groupBy(arr1, fp => getFileExtension(fp));

const mapping = {};
Object.entries(groupsbyFX).forEach(([fx, group]) => {
  const pairs = groupByCommonDirectories(group);
  mapping[fx] = pairs;
});

console.log(groupsbyFX)

function Test() {
  return (
    <div />
  );
}

export default Test;
