GITHUB_CLIENT_ID = '8577f13ddc81e2848b07'
GITHUB_STATE = '1337'

OAUTH_PROVIDER_GITHUB = 'github'
OAUTH_PROVIDER_ACTIVE_DIRECTORY = 'active_directory'

VALID_OAUTH_PROVIDERS = [
    OAUTH_PROVIDER_GITHUB,
    OAUTH_PROVIDER_ACTIVE_DIRECTORY,
]
