export const PAGE_NAME_EDIT = 'edit';
export const BLOCK_EXISTS_ERROR = '[ERR_BLOCK_EXISTS]';

export const EDIT_BEFORE_TAB_ALL_FILES = {
  uuid: 'All files',
};
export const EDIT_BEFORE_TAB_FILES_IN_PIPELINE = {
  uuid: 'Current blocks',
};
export const EDIT_BEFORE_TABS = [
  EDIT_BEFORE_TAB_ALL_FILES,
  EDIT_BEFORE_TAB_FILES_IN_PIPELINE,
];

export const CUSTOM_EVENT_BLOCK_OUTPUT_CHANGED = 'CUSTOM_EVENT_BLOCK_OUTPUT_CHANGED';
export const CUSTOM_EVENT_CODE_BLOCK_CHANGED = 'CUSTOM_EVENT_CODE_BLOCK_CHANGED';
export const CUSTOM_EVENT_COLUMN_SCROLLER_CURSOR_MOVED = 'CUSTOM_EVENT_COLUMN_SCROLLER_CURSOR_MOVED';
export const CUSTOM_EVENT_COLUMN_SCROLLER_RESET = 'CUSTOM_EVENT_COLUMN_SCROLLER_RESET';
export const CUSTOM_EVENT_COLUMN_SCROLLER_SCROLL_TO_BLOCK = 'CUSTOM_EVENT_COLUMN_SCROLLER_SCROLL_TO_BLOCK';
export const CUSTOM_EVENT_SYNC_COLUMN_POSITIONS = 'CUSTOM_EVENT_SYNC_COLUMN_POSITIONS';
