from enum import Enum

CONFIG_JSON_FILE = "config.json"
DATAFRAME_COLUMN_TYPES_FILE = "data_column_types.json"
DATAFRAME_CSV_FILE = "data.csv"
DATAFRAME_PARQUET_FILE = "data.parquet"
DATAFRAME_PARQUET_SAMPLE_FILE = "sample_data.parquet"
JOBLIB_FILE = "model.joblib"
JOBLIB_OBJECT_FILE = "object.joblib"
JSON_FILE = "data.json"
JSON_SAMPLE_FILE = "sample_data.json"
MATRIX_NPZ_FILE = "matrix.npz"
MATRIX_SAMPLE_NPZ_FILE = "matrix.npz"
MEDIA_IMAGE_VISUALIZATION_FILE = "visualization.png"
METADATA_FILE = "type.json"
UBJSON_MODEL_FILENAME = "model.ubj"


class VariableType(str, Enum):
    CUSTOM_OBJECT = "custom_object"
    DATAFRAME = "dataframe"
    DATAFRAME_ANALYSIS = "dataframe_analysis"
    DICTIONARY_COMPLEX = "dictionary_complex"
    GEO_DATAFRAME = "geo_dataframe"
    ITERABLE = "iterable"
    LIST_COMPLEX = "list_complex"
    MATRIX_SPARSE = "matrix_sparse"
    MODEL_SKLEARN = "model_sklearn"
    MODEL_XGBOOST = "model_xgboost"
    POLARS_DATAFRAME = "polars_dataframe"
    SERIES_PANDAS = "series_pandas"
    SPARK_DATAFRAME = "spark_dataframe"
