name: 'base'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'base'

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'
