export const CUSTOM_EVENT_NAME_APPLICATION_STATE_CHANGED = 'CUSTOM_EVENT_NAME_APPLICATION_STATE_CHANGED';
export const CUSTOM_EVENT_NAME_COMMAND_CENTER = 'CUSTOM_EVENT_NAME_COMMAND_CENTER';
export const CUSTOM_EVENT_NAME_COMMAND_CENTER_OPEN = 'CUSTOM_EVENT_NAME_COMMAND_CENTER_OPEN';
export const CUSTOM_EVENT_NAME_COMMAND_CENTER_STATE_CHANGED = 'CUSTOM_EVENT_NAME_COMMAND_CENTER_STATE_CHANGED';
export const CUSTOM_EVENT_NAME_FILE_OR_FOLDER_UPDATE = 'CUSTOM_EVENT_NAME_FILE_OR_FOLDER_UPDATE';
export const CUSTOM_EVENT_NAME_FOLDER_EXPAND = 'CUSTOM_EVENT_NAME_FOLDER_EXPAND';

export enum CustomEventUUID {
  COMMAND_CENTER_ENABLED = 'COMMAND_CENTER_ENABLED',
}
