export enum CustomAppEventEnum {
  APP_RECT_UPDATED = 'app_rect_updated',
  APP_UPDATED = 'app_updated',
  APP_STARTED = 'app_started',
  APP_STOPPED = 'app_stopped',
  CODE_EXECUTION_RESULT = 'code_execution_result',
  CONNECT_EVENT_STREAM = 'connect_event_stream',
  DISCONNECT_EVENT_STREAM = 'disconnect_event_stream',
  NODE_DROPPED = 'node_dropped',
  NODE_LAYOUTS_CHANGED = 'node_layouts_changed',
  NODE_MOUNTED = 'node.mounted',
  NODE_RECT_UPDATED = 'node_rect_updated',
  CODE_EXECUTION_SUBMITTED = 'code_execution_submitted',
  PORTAL_MOUNTED = 'portal.mounted',
  START_APP = 'start_app',
  START_DRAGGING = 'start_dragging',
  STOPPING_APP = 'stopping_app',
  STOP_APP = 'stop_app',
  UPDATE_NODE_LAYOUTS = 'update_node_layouts',
}
