export enum CustomAppEventEnum {
  NODE_DROPPED = 'NODE_DROPPED',
  START_DRAGGING = 'START_DRAGGING',
  START_APP = 'START_APP',
  STOP_APP = 'STOP_APP',
  STOPPING_APP = 'STOPPING_APP',
  APP_STARTED = 'APP_STARTED',
  APP_STOPPED = 'APP_STOPPED',
  NODE_MOUNTED = 'NODE_MOUNTED',
  APP_RECT_UPDATED = 'APP_RECT_UPDATED',
}
