"""Add description to pipeline_schedule

Revision ID: 117f8c3b9c42
Revises: a38d30f2541c
Create Date: 2023-08-31 17:59:19.470477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117f8c3b9c42'
down_revision = 'a38d30f2541c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_schedule', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
