"""Add repo name to pipeline schedule

Revision ID: 3ea13551cdfe
Revises: 83a74eca6ea1
Create Date: 2023-05-29 07:31:15.808874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea13551cdfe'
down_revision = '83a74eca6ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    with op.batch_alter_table('pipeline_schedule', schema=None) as batch_op:
        batch_op.drop_column('repo_name')

    # ### end Alembic commands ###
