"""Add executor_type to pipeline_run.

Revision ID: 66e67039b8a2
Revises: 21e31d66ccea
Create Date: 2023-05-12 11:20:50.288324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e67039b8a2'
down_revision = '21e31d66ccea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executor_type', sa.Enum('LOCAL_PYTHON', 'ECS', 'GCP_CLOUD_RUN', 'K8S', 'PYSPARK', name='executortype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.drop_column('executor_type')

    # ### end Alembic commands ###
