"""Add settings to backfill

Revision ID: b9a2d6d0a2c7
Revises: df2c4628b81b
Create Date: 2024-02-20 17:18:32.816138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a2d6d0a2c7'
down_revision = 'df2c4628b81b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backfill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backfill', schema=None) as batch_op:
        batch_op.drop_column('settings')

    # ### end Alembic commands ###
