"""update enums

Revision ID: d8c20c5e69fa
Revises: 7ac6fed06918
Create Date: 2023-01-05 11:18:56.554355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c20c5e69fa'
down_revision = '7ac6fed06918'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
