description: Fraud Detection Template
name: fraud_detection
pipeline:
  blocks:
  - all_upstream_blocks_executed: true
    color: null
    configuration: {}
    downstream_blocks:
    - dauntless_forest
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: eccentric potion
    retry_config: null
    status: not_executed
    timeout: null
    type: data_loader
    upstream_blocks: []
    uuid: eccentric_potion
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - curious_core
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: dauntless forest
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - eccentric_potion
    uuid: dauntless_forest
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - beautiful_shield
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: curious core
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - dauntless_forest
    uuid: curious_core
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - withered_haiku
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: beautiful shield
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - curious_core
    uuid: beautiful_shield
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - chromatic_shape
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: withered haiku
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - beautiful_shield
    uuid: withered_haiku
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - flawless_sea
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: chromatic shape
    retry_config: null
    status: not_executed
    timeout: null
    type: transformer
    upstream_blocks:
    - withered_haiku
    uuid: chromatic_shape
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks:
    - wavy_voice
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: flawless sea
    retry_config: null
    status: not_executed
    timeout: null
    type: model_maker
    upstream_blocks:
    - chromatic_shape
    uuid: flawless_sea
  - all_upstream_blocks_executed: false
    color: null
    configuration: {}
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: wavy voice
    retry_config: null
    status: not_executed
    timeout: null
    type: data_exporter
    upstream_blocks:
    - flawless_sea
    uuid: wavy_voice
  cache_block_output_in_memory: false
  callbacks: []
  concurrency_config: {}
  conditionals: []
  created_at: '2026-04-09 20:42:53.224717+00:00'
  data_integration: null
  description: Created from "Fraud Detection" Template
  executor_config: {}
  executor_count: 1
  executor_type: null
  extensions: {}
  name: fraud_detection
  notification_config: {}
  remote_variables_dir: null
  retry_config: {}
  run_pipeline_in_one_process: false
  settings:
    triggers: null
  spark_config: {}
  tags:
  - fraud
  - from-template
  type: python
  uuid: fraud_detection
  variables_dir: /home/src/mage_data/b2mage-base
  widgets: []
tags: []
user:
  username: admin
