connector_type: nats
server_url: "nats://localhost:4222"
subject: subject_name

# Optional: Specify more subjects
# subjects:
#   - subject1
#   - subject2

# Optional: Batch size and timeout for reading messages
batch_size: 100
timeout_ms: 5000

# Optional: TLS configuration
use_tls: false
# cafile: "path/to/ca.pem"
# certfile: "path/to/client-cert.pem"
# keyfile: "path/to/client-key.pem"
# tls_hostname: "example.com"

# Optional: User credentials
# user_credentials: "/path/to/secret.creds"

# Optional: Consumer name for pull-based subscription
consumer_name: "my_consumer"
