export type ThemeType = {
  accent: {
    alert: string;
    blue: string;
    blueLight: string;
    contentDefaultTransparent: string;
    cyan: string;
    cyanLight: string;
    cyanTransparent: string;
    dbt: string;
    dbtDark: string;
    dbtLight: string;
    info: string;
    infoTransparent: string;
    negative: string;
    negativeTransparent: string;
    pink: string;
    pinkLight: string;
    positive: string;
    primaryTransparent: string;
    purple: string;
    purpleLight: string;
    rose: string;
    roseLight: string;
    sky: string;
    skyLight: string;
    teal: string;
    tealLight: string;
    warning: string;
    warningTransparent: string;
    yellow: string;
    yellowLight: string;
  };
  background: {
    blackTransparent: string;
    blackTransparentDark: string;
    chartBlock: string;
    codeArea: string;
    codeTextarea: string;
    danger: string;
    dark: string;
    dashboard: string;
    dashboardTransparent: string;
    header: string;
    menu: string;
    muted: string;
    navigation: string;
    output: string;
    page: string;
    panel: string;
    panelTransparent: string;
    popup: string;
    row: string;
    row2: string;
    scrollbarThumb: string;
    scrollbarThumbHover: string;
    scrollbarTrack: string;
    success: string;
    successLight: string;
    table: string;
    tag: string;
  };
  borders: {
    contrast: string;
    danger: string;
    dark: string;
    info: string;
    light: string;
    medium: string;
    success: string;
  };
  brand: {
    earth100: string;
    earth200: string;
    earth300: string;
    earth400: string;
    earth400Transparent: string;
    earth500: string;
    energy100: string;
    energy200: string;
    energy300: string;
    energy400: string;
    energy400Transparent: string;
    energy500: string;
    fire100: string;
    fire200: string;
    fire300: string;
    fire400: string;
    fire400Transparent: string;
    fire500: string;
    stone100: string;
    stone200: string;
    stone400: string;
    stone500: string;
    water100: string;
    water200: string;
    water300: string;
    water400: string;
    water400Transparent: string;
    water500: string;
    wind100: string;
    wind200: string;
    wind300: string;
    wind400: string;
    wind400SuperTransparent: string;
    wind400Transparent: string;
    wind500: string;
  };
  chart: {
    backgroundDanger: string,
    backgroundPrimary: string,
    backgroundSecondary: string,
    backgroundTertiary: string,
    button1: string;
    button2: string;
    button3: string;
    button4: string;
    button5: string;
    danger: string,
    lines: string;
    primary: string;
    secondary: string;
    tertiary: string,
  };
  content: {
    active: string;
    default: string;
    disabled: string;
    muted: string;
  };
  contentInverted: {
    active: string;
  };
  elevation: {
    visualizationAccent: string;
    visualizationAccentAlt: string;
  };
  feature: {
    active: string;
    disabled: string;
  };
  interactive: {
    activeBorder: string;
    blackBackgroundTransparent: string;
    dangerBorder: string;
    defaultBackgroundTransparent: string;
    defaultBorder: string;
    disabledBorder: string;
    focusBackground: string;
    focusBorder: string;
    hoverBackground: string;
    hoverBackgroundTransparent: string;
    hoverBlackBackgroundTransparent: string;
    hoverBorder: string;
    linkPrimary: string;
    linkSecondary: string;
  };
  loader: {
    color: string;
    colorInverted: string;
  };
  monotone: {
    black: string;
    blackTransparent: string;
    gray: string;
    grey100: string;
    grey200: string;
    grey300: string;
    grey400: string;
    grey500: string;
    purple: string;
    white: string;
    whiteTransparent: string;
  };
  neutral: {
    n100: string;
    n200: string;
    n300: string;
    n400: string;
    n500: string;
  };
  progress: {
    negative: string;
    positive: string;
  };
  shadow: {
    base: string;
    menu: string;
    popup: string;
  };
  text: {
    fileBrowser: string;
  };
};
