import {
  BLACK,
  BLUE,
  BLUE_DARK,
  BLUE_HIGHLIGHT,
  BLUE_HIGHLIGHT_LIGHT,
  BLUE_LIGHT,
  BLUE_SKY,
  BLUE_SKY_DARK,
  BLUE_TEXT,
  BLUE_TRANSPARENT,
  DARK_GRAY_LINES,
  DBT_ORANGE,
  DBT_ORANGE_TRANSPARENT,
  DBT_ORANGE_TRANSPARENT_DARK,
  GRAY_LINES,
  GRAY,
  GRAY_HIGHLIGHT,
  GREEN,
  LIGHT,
  LIME,
  GREY100,
  GREY200,
  GREY300,
  GREY400,
  GREY500,
  LIME_DARK,
  LIME_XLIGHT,
  LIME_TEXT,
  LIME_TRASPARENT,
  NAVY,
  PEACH,
  PINK,
  PINK_TRANSPARENT,
  PURPLE,
  PURPLE2,
  PURPLE_DARK,
  PURPLE_DISABLED,
  PURPLE_HIGHLIGHT,
  PURPLE_LIGHT,
  PURPLE_TRANSPARENT,
  RED,
  RED_LIGHT,
  RED_XLIGHT,
  SILVER,
  WHITE,
  YELLOW,
  YELLOW_TRANSPARENT,
} from '../colors/main';
import {
  DARK_CONTENT_ACTIVE,
  DARK_CONTENT_DEFAULT,
  DARK_CONTENT_DEFAULT_TRANSPARENT,
  DARK_CONTENT_DISABLED,
  DARK_CONTENT_INVERTED,
  DARK_CONTENT_MUTED,
} from '../colors/content';
import PopupMenu from '@oracle/components/PopupMenu';
import { redirect } from 'next/dist/server/api-utils';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  accent: {
    alert: '#F6540B',
    blue: BLUE_DARK,
    blueLight: BLUE_TRANSPARENT,
    contentDefaultTransparent: DARK_CONTENT_DEFAULT_TRANSPARENT,
    cyan: '#4A9AED',
    cyanLight: '#4A9AED',
    cyanTransparent: '#4A9AED',
    dbt: DBT_ORANGE,
    dbtDark: DBT_ORANGE_TRANSPARENT_DARK,
    dbtLight: DBT_ORANGE_TRANSPARENT,
    info: '#00ABFF',
    infoTransparent: 'rgba(0, 171, 255, 0.5)',
    negative: '#FF1E59',
    negativeTransparent: 'rgba(255, 30, 89, 0.3)',
    pink: PINK,
    pinkLight: PINK_TRANSPARENT,
    positive: '#00A81A',
    primaryTransparent: 'rgba(155, 108, 167, 0.5)',
    purple: PURPLE_DARK,
    purpleLight: PURPLE_TRANSPARENT,
    rose: '#D1A2AB',
    roseLight: 'rgba(209, 162, 171, 0.5)',
    sky: BLUE_SKY_DARK,
    skyLight: 'rgba(106, 161, 224, 0.5)',
    teal: '#00B4CC',
    tealLight: 'rgba(0, 180, 204, 0.5)',
    warning: '#DD9900',
    warningTransparent: 'rgba(221, 153, 0, 0.5)',
    yellow: YELLOW,
    yellowLight: YELLOW_TRANSPARENT,
  },
  background: {
    codeArea: '#F0F0F0',
    danger: RED_XLIGHT,
    dark: GRAY,
    chartBlock: '#D6D7D9',
    codeTextarea: '#000000',
    content: '#1B1C20',
    dashboard: SILVER,
    header: '#FFFFFF',
    menu: NAVY,
    muted: SILVER,
    navigation: '#EDEDED',
    output: '#EFEFEF',
    page: '#FFFFFF',
    panel: '#FFFFFF',
    panelTransparent: '#FFFFFF',
    row: LIGHT,
    scrollbarThumb: 'rgba(0, 0, 0, 0.5)',
    scrollbarThumbHover: 'rgba(255, 255, 255, 0.3)',
    scrollbarTrack: 'rgba(39, 42, 47, 0.3)',
    success: LIME_XLIGHT,
    table: WHITE,
    tag: '#EFF0F2',
  },
  borders: {
    button: '#D3DAE6',
    contrast: '#D3DAE6',
    danger: RED,
    dark: '#000000',
    info: YELLOW,
    light: '#EFEFEF',
    medium: '#D3DAE6',
    medium2: '#C5CBD6',
    success: GREEN,
  },
  brand: {
    earth100: '#C6EEDB',
    earth200: '#9DDFBF',
    earth300: '#6BBF96',
    earth400: '#37A46F',
    earth400Transparent: 'rgba(55, 164, 111, 0.4)',
    earth500: '#00954C',
    energy100: '#FFF4BA',
    energy200: '#FFED92',
    energy300: '#FFE662',
    energy400: '#FFDA19',
    energy400Transparent: 'rgba(255, 218, 25, 0.04)',
    energy500: '#F6C000',
    fire100: '#FFD7E0',
    fire200: '#FFA3B9',
    fire300: '#FF547D',
    fire400: '#FF144D',
    fire400Transparent: 'rgba(255, 20, 77, 0.4)',
    fire500: '#EB0032',
    stone100: '#F3E6D7',
    stone200: '#E3D4C2',
    stone400: '#BFA78B',
    stone500: '#AF8859',
    water100: '#BDCEFF',
    water200: '#81A1FF',
    water300: '#517DFF',
    water400: '#2A60FE',
    water400Transparent: 'rgba(42, 96, 254, 0.4)',
    water500: '#0F4CFF',
    wind100: '#EEEAFF',
    wind200: '#CCC1F4',
    wind300: '#A698DD',
    wind400: '#6B50D7',
    wind400SuperTransparent: 'rgba(107, 80, 215, 0.12)',
    wind400Transparent: 'rgba(107, 80, 215, 0.4)',
    wind500: '#4E32BC',
  },
  chart: {
    backgroundDanger: RED_LIGHT,
    backgroundPrimary: PURPLE_LIGHT,
    backgroundSecondary: RED_LIGHT,
    backgroundTertiary: BLUE_HIGHLIGHT_LIGHT,
    button1: BLUE_DARK,
    button2: YELLOW,
    button3: LIME,
    danger: RED,
    lines: '#9B6CA7',
    primary: PURPLE,
    secondary: RED,
    tertiary: BLUE_HIGHLIGHT,
  },
  content: {
    active: BLACK,
    default: BLACK,
    disabled: GRAY_LINES,
    inverted: WHITE,
    muted: GRAY,
  },
  elevation: {
    visualizationAccent: '#996CFF',
    visualizationAccentAlt: '#C1ACF7',
  },
  feature: {
    active: PURPLE_HIGHLIGHT,
    disabled: PURPLE_DISABLED,
  },
  icons: {
    neutral: '#787878',
  },
  interactive: {
    activeBorder: BLACK,
    checked: PURPLE_LIGHT,
    dangerBorder: RED,
    defaultBackground: '#EFF0F2',
    defaultBackgroundTransparent: 'rgba(54, 56, 63, 0.6)',
    defaultBorder: '#D3DAE6',
    disabledBorder: GRAY,
    focusBackground: GRAY,
    focusBorder: BLUE_HIGHLIGHT,
    hoverBackground: '#E3E4E6',
    hoverBorder: DARK_GRAY_LINES,
    linkPrimary: '#4A9AED',
    linkPrimaryHover: '#CCE4F5',
    linkPrimaryLight: BLUE_LIGHT,
    linkSecondary: PURPLE,
    linkSecondaryDisabled: PURPLE_LIGHT,
    linkText: BLUE_SKY_DARK,
    linkTextLight: BLUE_SKY,
    purple: PURPLE2,
    rowHoverBackground: 'rgba(0, 0, 0, 0.1)',
    transparent: 'rgba(255, 255, 255, 0)',
  },
  loader: {
    color: LIME_DARK,
    colorInverted: '#EB0032',
  },
  monotone: {
    black: BLACK,
    blackTransparent: 'rgba(0, 0, 0, 0.6)',
    gray: GRAY,
    grey100: '#F2F2F2',
    grey200: '#D5D7DC',
    grey300: '#B4B8C0',
    grey400: '#70747C',
    grey500: '#28292C',
    purple: PURPLE,
    white: WHITE,
  },
  neutral: {
    n100: '#E7E8EA',
    n200: '#D8DADE',
    n300: '#CBCCD0',
    n400: '#BCBEC4',
    n500: '#AEB0B6',
  },
  progress: {
    negative: RED,
    positive: PURPLE,
  },
  shadow: {
    base: '12px 40px 120px rgba(106, 117, 139, 0.4)',
    frame: '0px 10px 40px rgba(0, 0, 0, 0.26)',
    menu: '4px 10px 20px rgba(6, 6, 6, 0.12)',
    popup: '10px 20px 40px rgba(0, 0, 0, 0.2)',
    small: '0px, 4px, rgba(0, 0, 0, 0.25)',
    window: '0px 10px 60px rgba(0, 0, 0, 0.7)',
  },
  status: {
    negative: RED,
    positive: LIME_TEXT,
  },
};