DATA_TYPE_BOOLEAN = 'BOOLEAN'
DATA_TYPES_BOOLEAN = [
    'BOOL',
    DATA_TYPE_BOOLEAN,
]

DATA_TYPE_BIGINT = 'BIGINT'
DATA_TYPES_INTEGER = [
    DATA_TYPE_BIGINT,
    'INT',
    'INT2',
    'INT4,',
    'INT8',
    'INTEGER',
]

DATA_TYPE_DOUBLE_PRECISION = 'DOUBLE PRECISION'
DATA_TYPES_NUMBER = [
    'DECIMAL',
    DATA_TYPE_DOUBLE_PRECISION,
    'FLOAT',
    'FLOAT4',
    'FLOAT8',
    'NUMERIC',
    'REAL',
    'SMALLINT',
]

DATA_TYPES_DATE = [
    'DATE',
    'TIME WITH TIME ZONE',
    'TIME WITHOUT TIME ZONE',
    'TIME',
    'TIMESTAMP WITH TIME ZONE',
    'TIMESTAMP WITHOUT TIME ZONE',
    'TIMESTAMP',
    'TIMESTAMPTZ',
    'TIMETZ',
]

DATA_TYPE_TEXT = 'TEXT'
DATA_TYPE_VARCHAR = 'VARCHAR'
DATA_TYPES_STRING = [
    'BPCHAR',
    'CHAR',
    'CHARACTER VARYING',
    'CHARACTER',
    'NCHAR',
    'NVARCHAR',
    DATA_TYPE_TEXT,
    DATA_TYPE_VARCHAR,
]

DATA_TYPES_OTHER = [
    'GEOMETRY',
    'HLLSKETCH',
]
