COLUMN_FORMAT_DATETIME = 'date-time'

COLUMN_TYPE_BOOLEAN = 'boolean'
COLUMN_TYPE_INTEGER = 'integer'
COLUMN_TYPE_NUMBER = 'number'
COLUMN_TYPE_OBJECT = 'object'
COLUMN_TYPE_STRING = 'string'

KEY_BOOKMARK_PROPERTIES = 'bookmark_properties'
KEY_KEY_PROPERTIES = 'key_properties'
KEY_RECORD = 'record'
KEY_REPLICATION_METHOD = 'replication_method'
KEY_SCHEMA = 'schema'
KEY_STREAM = 'stream'
KEY_TYPE = 'type'
KEY_UNIQUE_CONFLICT_METHOD = 'unique_conflict_method'
KEY_UNIQUE_CONSTRAINTS = 'unique_constraints'
KEY_VALUE = 'value'

REPLICATION_METHOD_FULL_TABLE = 'FULL_TABLE'
REPLICATION_METHOD_INCREMENTAL = 'INCREMENTAL'

TYPE_RECORD = 'RECORD'
TYPE_SCHEMA = 'SCHEMA'
TYPE_STATE = 'STATE'

UNIQUE_CONFLICT_METHOD_IGNORE = 'IGNORE'
UNIQUE_CONFLICT_METHOD_UPDATE = 'UPDATE'
