COLUMN_FORMAT_DATETIME = 'date-time'

COLUMN_TYPE_ARRAY = 'array'
COLUMN_TYPE_BOOLEAN = 'boolean'
COLUMN_TYPE_INTEGER = 'integer'
COLUMN_TYPE_NULL = 'null'
COLUMN_TYPE_NUMBER = 'number'
COLUMN_TYPE_OBJECT = 'object'
COLUMN_TYPE_STRING = 'string'

INCLUSION_AUTOMATIC = 'automatic'
INCLUSION_AVAILABLE = 'available'
INCLUSION_UNSUPPORTED = 'unsupported'

METADATA_KEY_INCLUSION = 'inclusion'
METADATA_KEY_SELECTED = 'selected'

REPLICATION_METHOD_FULL_TABLE = 'FULL_TABLE'
REPLICATION_METHOD_INCREMENTAL = 'INCREMENTAL'

UNIQUE_CONFLICT_METHOD_IGNORE = 'IGNORE'
UNIQUE_CONFLICT_METHOD_UPDATE = 'UPDATE'

BATCH_FETCH_LIMIT = 1000
